In [2]:
# Import torch
import torch
# Create random tensor
A_tensor = torch.rand(size=(7,7))
A_tensor, A_tensor.shape, A_tensor.ndim


(tensor([[0.5358, 0.7856, 0.5339, 0.3616, 0.3136, 0.7445, 0.9812],
         [0.2494, 0.6654, 0.6311, 0.6063, 0.2933, 0.2109, 0.2380],
         [0.7298, 0.1347, 0.4899, 0.8545, 0.5352, 0.7327, 0.6132],
         [0.4053, 0.1031, 0.2746, 0.4038, 0.9603, 0.4649, 0.2268],
         [0.7826, 0.4654, 0.8578, 0.8622, 0.1199, 0.5121, 0.5499],
         [0.4727, 0.3826, 0.7039, 0.5651, 0.7718, 0.2103, 0.2158],
         [0.1162, 0.7696, 0.3069, 0.1526, 0.0825, 0.1234, 0.2735]]),
 torch.Size([7, 7]),
 2)

In [3]:
# Create another random tensor
B_tensor = torch.rand(size=(1,7))
A_tensor, B_tensor
# Perform matrix multiplication
output_1 = torch.matmul(A_tensor, B_tensor.T)
output_1, output_1.shape


(tensor([[1.5615],
         [0.8536],
         [1.7403],
         [1.4954],
         [1.2257],
         [1.2265],
         [0.4217]]),
 torch.Size([7, 1]))

In [4]:
# Set manual seed
torch.manual_seed(0)
# Create two random tensors
A_tensor = torch.rand(size=(7,7))
B_tensor = torch.rand(size=(1,7))
A_tensor, B_tensor
# Matrix multiply tensors
output_2 = torch.matmul(A_tensor, B_tensor.T)
output_2, output_2.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

In [5]:
torch.cuda.manual_seed(1234)


In [6]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
device

# Create two random tensors on GPU
C_tensor = torch.rand(size=(2, 3)).to(device)
D_tensor = torch.rand(size=(2, 3)).to(device)

print(C_tensor)
print(D_tensor)

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')


In [7]:
# Perform matmul on tensor_A and tensor_B
output_3 = torch.matmul(C_tensor, D_tensor.T)
output_3, output_3.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [8]:
# Find max
print(f"Maximum: {output_3.max()}")

# Find min
print(f"Minimum: {output_3.min()}")

Maximum: 0.5617256760597229
Minimum: 0.3647301495075226


In [9]:
# Find arg max
print(f"Index where max value occurs: {output_3.argmax()}")

# Find arg min
print(f"Index where min value occurs: {output_3.argmin()}")

Index where max value occurs: 3
Index where min value occurs: 0


In [10]:
# Set seed
torch.manual_seed(7)

# Create random tensor
E_tensor = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
E_tensor_squeezed = E_tensor.squeeze()

# Print out tensors and their shapes
print(E_tensor, E_tensor.shape)
print(E_tensor_squeezed, E_tensor_squeezed.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
